<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e583feea-4054-43eb-81f0-14ddc3768b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'EasyAccounts')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Accounts&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d6271810-6ec5-4f2b-bb4b-b07686f85163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6cb2c8ee-e61b-4db7-847d-4690a0debce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://data-momentum-7717.my.salesforce.com/logos/Salesforce/EasyAccounts/logo.png?v=254.4</value>
      <webElementGuid>6420b4ae-039d-4e9d-8b89-2dae4dea1def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop&quot;]/div[@class=&quot;desktop container forceStyle oneOne navexDesktopLayoutContainer lafAppLayoutHost forceAccess&quot;]/div[@class=&quot;viewport supportVerticalNav&quot;]/section[@class=&quot;layoutContent stage panelSlide hasFixedFooter&quot;]/div[@class=&quot;verticalNavContainer one-primaryNav slds-scrollable_none slds-is-fixed runtime_sales_easyVerticalNavWrapper&quot;]/runtime_sales_easy-vertical-nav[1]/div[@class=&quot;verticalNavMenu&quot;]/ul[@class=&quot;verticalNavMenuList slds-text-align_center slds-text-color_inverse slds-var-m-top_medium&quot;]/li[@class=&quot;verticalNavMenuListItem slds-var-m-top_x-small&quot;]/runtime_sales_easy-vertical-nav-app-item[@class=&quot;navItem&quot;]/a[@class=&quot;slds-text-align_center slds-grid slds-media_center slds-grid_align-center appItem logo-type-bright&quot;]/span[@class=&quot;slds-grid slds-media_center slds-grid_align-center appItemImage&quot;]/img[1]</value>
      <webElementGuid>caaf55a4-1201-41d5-9612-cdf854efb2bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://data-momentum-7717.my.salesforce.com/logos/Salesforce/EasyAccounts/logo.png?v=254.4')]</value>
      <webElementGuid>fd4e9ba0-be8c-4a94-a503-9019ce1dbbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/runtime_sales_easy-vertical-nav-app-item/a/span/img</value>
      <webElementGuid>bab248e0-405d-4128-864c-2dbd584fb193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://data-momentum-7717.my.salesforce.com/logos/Salesforce/EasyAccounts/logo.png?v=254.4']</value>
      <webElementGuid>b567c334-784f-4e0a-ba77-aa417d927bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
