<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verification Code_RememberDeviceCheckbox</name>
   <tag></tag>
   <elementGuidId>7bd6a906-565e-4c6b-a493-de12efd87897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RememberDeviceCheckbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RememberDeviceCheckbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Don't ask again&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>072c6972-8f2a-4408-925d-1e49203c9239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>8ea38782-5e08-43fe-a5d5-3c8d259c2c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RememberDeviceCheckbox</value>
      <webElementGuid>0e7fe708-105c-4472-8213-b55017ad871a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RememberDevice</value>
      <webElementGuid>22a923c3-9adf-4d05-8e11-53a3f9fbe321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5676a29c-7dac-4ed9-853f-5e3234e4917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>571219cd-5451-44f0-a896-f59470627435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RememberDeviceCheckbox&quot;)</value>
      <webElementGuid>85dcf39d-4498-4496-84f3-1f61dee67423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RememberDeviceCheckbox']</value>
      <webElementGuid>aa996805-f17a-4fb4-bcc3-7725eb596c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RememberDeviceDiv']/input</value>
      <webElementGuid>3ac985d3-cd96-4c92-89bc-4bfa607bd7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d5076190-2217-469d-af29-9bc20f9d44b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'RememberDeviceCheckbox' and @name = 'RememberDevice' and @type = 'checkbox']</value>
      <webElementGuid>df16a098-3d07-4b70-90b4-d1b62a33eee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
